apiVersion: v1
kind: Pod
spec:
  containers:
  - volumeMounts:
    - mountPath: /v3io
      name: v3io-fuse
    - mountPath: /User
      name: v3io-fuse
      subPath: users//admin
    - mountPath: /igz/java/crash
      name: igz-java
    - mountPath: /igz/java/auth
      name: v3io-auth
    - mountPath: /dev/shm
      name: shm
    - mountPath: /var/run/iguazio/dayman
      name: v3iod-comm
    env:
    - name: IGZ_DATA_CONFIG_FILE
      value: /User/conf/spark/v3io.conf
    - name: CURRENT_NODE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
  volumes:
  - flexVolume:
      driver: v3io/fuse
      options:
        dirsToCreate: '[{"name": "users//admin", "permissions": 488}]'
      secretRef:
        name: jupyter-v3io-fuse
    name: v3io-fuse
  - emptyDir: {}
    name: igz-java
  - name: v3io-auth
    secret:
      defaultMode: 420
      secretName: jupyter-v3io-auth
  - hostPath:
      path: /dev/shm/default-tenant
      type: ""
    name: shm
  - hostPath:
      path: /var/run/iguazio/dayman/default-tenant
      type: ""
    name: v3iod-comm
