apiVersion: v1
kind: Pod
metadata:
  name: hadoop-master
  labels:
    name: hadoop
spec:
  serviceAccountName: hadoop-master
  hostname: hadoop-master
  subdomain: hadoop-domain
  containers:
  - name: master
    image: {{ .Values.hadoop.image }}:{{ .Values.hadoop.tag }}
    command: ["/usr/local/hadoop/sbin/bootstrap.sh"]
    args: ["master"]
    imagePullPolicy: {{ .Values.hadoop.pullPolicy }}
    env:
    - name: KRB5CCNAME
      value: {{ .Values.default_ccache_path}}/{{ .Values.ccache_filename }}
    volumeMounts:
    - mountPath: /hdfs
      name: hdfs-namenode-data
    - name: krb5-conf
      mountPath: /etc/krb5.conf
      subPath: krb5.conf
    - name: krb5-keytab
      mountPath: /etc/krb5.keytab
      subPath: hdfs.keytab
    - name: krb5-keytab
      mountPath: /etc/hdfs.jks
      subPath: hdfs.jks
    - name: ccache
      mountPath: {{ .Values.default_ccache_path }}

#  - name: krb-sidecar
#    image: {{ .Values.sidecar.image }}:{{ .Values.sidecar.tag }}
#    imagePullPolicy: {{ .Values.sidecar.pullPolicy }}
#    command: ["/rekinit.sh"]
#    env:
#    - name: PERIOD_SECONDS
#      value: "3600"
#    - name: OPTIONS
#      value: "-k"
#    - name: APPEND_OPTIONS
#      value: "iguazio"
#    volumeMounts:
#    - name: krb5-conf
#      mountPath: /etc/krb5.conf
#      subPath: krb5.conf
#    - name: sidecar-conf
#      mountPath: /rekinit.sh
#      subPath: rekinit.sh
#    - name: ccache
#      mountPath: {{ .Values.default_ccache_path }}
#    - name: krb5-keytab
#      mountPath: /etc/krb5.keytab
#      subPath: hdfs.keytab

  volumes:
  - name: hdfs-namenode-data
    persistentVolumeClaim:
      claimName: hdfs-nn-pvc
  - name: krb5-conf
    configMap:
      name: kuberos-kuberos-krb5-config
  - name: krb5-keytab
    secret:
      secretName: {{ .Values.krb_client_secret_name }}
  - name: sidecar-conf
    configMap:
      name: {{ .Values.sidecar.configmap }}
      defaultMode: 0755
  - name: ccache
    emptyDir:
      medium: Memory
