apiVersion: v1
kind: ServiceAccount
metadata:
  name: hadoop-master

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: secrets-configmaps-get-put
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "update", "create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "update", "create"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hadoop-master-role-binding
subjects:
- kind: ServiceAccount
  name: hadoop-master
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: secrets-configmaps-get-put
  apiGroup: rbac.authorization.k8s.io

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hadoop-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hadoop-role-binding
subjects:
- kind: ServiceAccount
  name: hadoop-master
roleRef:
  kind: Role
  name: hadoop-role
  apiGroup: rbac.authorization.k8s.io
